package com.myproject.questservice.domain.generator;

public enum StageType {
    QUEST_DESCRIPTION,
    QUEST_CONSTRAINTS,
    ACHIEVEMENT_RESOURCE_ANALYSIS,
    WORLD,
    ACHIEVEMENT_REALISATION,
    ACHIEVEMENT_INFORMATION_FLOW,
    ACHIEVEMENT_SCENES,
    FACTS,
    QUEST_OUTLINE,
    CHAPTERS,
    SCENES,
    QUEST_GRAPH
}
