package com.myproject.questservice.domain.generator;

public enum StageType {
    FIRST_SCENE,
    QUEST_DESCRIPTION,
    QUEST_CONSTRAINTS,
    ACHIEVEMENT_RESOURCE_ANALYSIS,
    WORLD,
    ACHIEVEMENT_REALISATION,
    ACHIEVEMENT_INFORMATION_FLOW,
    KNOWLEDGE_CHAIN,
    ACHIEVEMENT_SCENES,
    ACTION_QUESTS,
    FACTS,
    QUEST_OUTLINE,
    CHAPTERS,
    SCENES,
    QUEST_GRAPH
}
