package com.myproject.questservice.application.service.generator.stage;

import com.fasterxml.jackson.databind.JsonNode;
import com.myproject.questservice.application.port.out.generator.AiClient;
import com.myproject.questservice.application.service.NotFoundException;
import com.myproject.questservice.application.service.generator.ProjectRepository;
import com.myproject.questservice.domain.generator.QuestProject;
import com.myproject.questservice.domain.generator.StageType;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;

import java.util.UUID;

@Component
@RequiredArgsConstructor
public class MysteryStageRunner implements StageRunner {
    private static final String SYSTEM_PROMPT = """
            You are a Mystery Designer for a KR2-style investigation quest.

            Your task is to create only the central mystery blueprint.

            You are NOT a quest writer.
            You are NOT creating scenes.
            You are NOT creating dialogues.

            Do not create:
            - locations
            - NPCs
            - items
            - quests flow
            - gameplay scenes

            Those will be generated by later stages.

            Your goal is to design a strong mystery foundation that other stages can use.

            The mystery should follow these principles:

            - investigation-driven
            - player discovers truth gradually
            - multiple possible interpretations
            - hidden real explanation
            - final reveal that changes the interpretation of previous events

            Create:

            1. Title
            2. Initial situation / hook
            3. Main mystery question
            4. True explanation
            5. Two believable false explanations
            6. Final revelation

            Return ONLY valid JSON.

            JSON schema:

            {
              "title": "",
              "hook": "",
              "question": "",
              "truth": "",
              "false_theories": [
                "",
                ""
              ],
              "final_reveal": ""
            }
            """;

    private final ProjectRepository projectRepository;
    private final AiClient aiClient;

    @Override
    public StageType type() {
        return StageType.MYSTERY;
    }

    @Override
    public JsonNode generate(UUID projectId) {
        QuestProject project = projectRepository.findById(projectId)
                .orElseThrow(() -> new NotFoundException("Project not found: " + projectId));
        String userPrompt = buildUserPrompt(project);
        return aiClient.generate(SYSTEM_PROMPT, userPrompt);
    }

    private String buildUserPrompt(QuestProject project) {
        String style = project.getQuestStyle() == null || project.getQuestStyle().isBlank()
                ? "classic-adventure"
                : project.getQuestStyle().trim();
        return """
                Project context:
                - project_name: %s
                - quest_style: %s

                Use this context for tone and framing.
                Output must strictly follow the JSON schema from system prompt.
                """.formatted(project.getName(), style);
    }
}
